"""Add agent card system - dynamic agent discovery and registration

Revision ID: 7553d11049e1
Revises: 8a05ad6ac1fd
Create Date: 2025-12-05 22:20:14.827886

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7553d11049e1'
down_revision: Union[str, None] = '8a05ad6ac1fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_cards',
    sa.Column('agent_id', sa.String(), nullable=False),
    sa.Column('agent_name', sa.String(), nullable=False),
    sa.Column('agent_type', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('version', sa.String(), nullable=False),
    sa.Column('capabilities', sa.JSON(), nullable=True),
    sa.Column('specialties', sa.JSON(), nullable=True),
    sa.Column('supported_languages', sa.JSON(), nullable=True),
    sa.Column('base_class', sa.String(), nullable=True),
    sa.Column('config_schema', sa.JSON(), nullable=True),
    sa.Column('default_config', sa.JSON(), nullable=True),
    sa.Column('author', sa.String(), nullable=True),
    sa.Column('homepage', sa.String(), nullable=True),
    sa.Column('license', sa.String(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('trust_score', sa.Float(), nullable=True),
    sa.Column('total_invocations', sa.Integer(), nullable=True),
    sa.Column('success_rate', sa.Float(), nullable=True),
    sa.Column('average_rating', sa.Float(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('certificate_serial', sa.String(), nullable=True),
    sa.Column('trust_domain', sa.String(), nullable=True),
    sa.Column('module_path', sa.String(), nullable=False),
    sa.Column('class_name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('agent_id')
    )
    op.create_index(op.f('ix_agent_cards_agent_name'), 'agent_cards', ['agent_name'], unique=False)
    op.create_index(op.f('ix_agent_cards_agent_type'), 'agent_cards', ['agent_type'], unique=False)
    op.create_index(op.f('ix_agent_cards_status'), 'agent_cards', ['status'], unique=False)
    op.create_index(op.f('ix_agent_cards_trust_score'), 'agent_cards', ['trust_score'], unique=False)
    op.create_table('agent_invocations',
    sa.Column('invocation_id', sa.String(), nullable=False),
    sa.Column('agent_id', sa.String(), nullable=False),
    sa.Column('workflow_id', sa.String(), nullable=True),
    sa.Column('mission_id', sa.String(), nullable=True),
    sa.Column('stage', sa.String(), nullable=True),
    sa.Column('input_data', sa.JSON(), nullable=True),
    sa.Column('output_data', sa.JSON(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('duration', sa.Float(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('feedback', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agent_cards.agent_id'], ),
    sa.PrimaryKeyConstraint('invocation_id')
    )
    op.create_index(op.f('ix_agent_invocations_agent_id'), 'agent_invocations', ['agent_id'], unique=False)
    op.create_index(op.f('ix_agent_invocations_mission_id'), 'agent_invocations', ['mission_id'], unique=False)
    op.create_index(op.f('ix_agent_invocations_status'), 'agent_invocations', ['status'], unique=False)
    op.create_index(op.f('ix_agent_invocations_workflow_id'), 'agent_invocations', ['workflow_id'], unique=False)
    op.create_table('agent_templates',
    sa.Column('template_id', sa.String(), nullable=False),
    sa.Column('template_name', sa.String(), nullable=False),
    sa.Column('template_type', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('base_agent_card_id', sa.String(), nullable=True),
    sa.Column('configuration', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['base_agent_card_id'], ['agent_cards.agent_id'], ),
    sa.PrimaryKeyConstraint('template_id')
    )
    op.create_index(op.f('ix_agent_templates_template_name'), 'agent_templates', ['template_name'], unique=False)
    op.create_index(op.f('ix_agent_templates_template_type'), 'agent_templates', ['template_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_agent_templates_template_type'), table_name='agent_templates')
    op.drop_index(op.f('ix_agent_templates_template_name'), table_name='agent_templates')
    op.drop_table('agent_templates')
    op.drop_index(op.f('ix_agent_invocations_workflow_id'), table_name='agent_invocations')
    op.drop_index(op.f('ix_agent_invocations_status'), table_name='agent_invocations')
    op.drop_index(op.f('ix_agent_invocations_mission_id'), table_name='agent_invocations')
    op.drop_index(op.f('ix_agent_invocations_agent_id'), table_name='agent_invocations')
    op.drop_table('agent_invocations')
    op.drop_index(op.f('ix_agent_cards_trust_score'), table_name='agent_cards')
    op.drop_index(op.f('ix_agent_cards_status'), table_name='agent_cards')
    op.drop_index(op.f('ix_agent_cards_agent_type'), table_name='agent_cards')
    op.drop_index(op.f('ix_agent_cards_agent_name'), table_name='agent_cards')
    op.drop_table('agent_cards')
    # ### end Alembic commands ###
