"""Initial schema with governance models

Revision ID: 7e9a3ca1116e
Revises: 
Create Date: 2025-12-05 12:08:22.149928

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e9a3ca1116e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('governance_decisions',
    sa.Column('decision_id', sa.String(), nullable=False),
    sa.Column('workflow_id', sa.String(), nullable=False),
    sa.Column('stage', sa.String(), nullable=False),
    sa.Column('decision', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('trust_score', sa.Float(), nullable=False),
    sa.Column('policy_violations', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('decision_id')
    )
    op.create_index(op.f('ix_governance_decisions_workflow_id'), 'governance_decisions', ['workflow_id'], unique=False)
    op.create_table('governance_policies',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('min_trust_score', sa.Float(), nullable=False),
    sa.Column('auto_approve_threshold', sa.Float(), nullable=False),
    sa.Column('require_security_review', sa.Boolean(), nullable=False),
    sa.Column('require_code_review', sa.Boolean(), nullable=False),
    sa.Column('allowed_languages', sa.JSON(), nullable=False),
    sa.Column('max_cost_per_mission', sa.Float(), nullable=True),
    sa.Column('enable_breakpoints', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('governance_policies')
    op.drop_index(op.f('ix_governance_decisions_workflow_id'), table_name='governance_decisions')
    op.drop_table('governance_decisions')
    # ### end Alembic commands ###
