"""Add policy name, description, and is_active fields

Revision ID: 8a05ad6ac1fd
Revises: 7e9a3ca1116e
Create Date: 2025-12-05 12:39:58.776807

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a05ad6ac1fd'
down_revision: Union[str, None] = '7e9a3ca1116e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # SQLite doesn't support ALTER COLUMN, so we use server defaults
    # These defaults will backfill existing rows and also apply to new rows
    op.add_column('governance_policies', sa.Column('name', sa.String(), nullable=False, server_default='Default Policy'))
    op.add_column('governance_policies', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('governance_policies', sa.Column('is_active', sa.Boolean(), nullable=False, server_default='1'))

    op.create_index(op.f('ix_governance_policies_is_active'), 'governance_policies', ['is_active'], unique=False)
    op.create_unique_constraint(None, 'governance_policies', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'governance_policies', type_='unique')
    op.drop_index(op.f('ix_governance_policies_is_active'), table_name='governance_policies')
    op.drop_column('governance_policies', 'is_active')
    op.drop_column('governance_policies', 'description')
    op.drop_column('governance_policies', 'name')
    # ### end Alembic commands ###
