"""
Team Agent Roles V2 - With real run() methods, logging, and tape integration.
"""

from typing import Dict, Any, Optional
import sys
from pathlib import Path

# Add utils to path
sys.path.insert(0, str(Path(__file__).parent.parent.parent))

from utils.logging import get_logger


class BaseAgent:
    """Base class for all agents with logging and tape integration."""
    
    def __init__(self, workflow_id: Optional[str] = None):
        """Initialize agent with logger."""
        self.workflow_id = workflow_id
        self.logger = get_logger(self.__class__.__name__.lower(), workflow_id)
    
    def run(self, input_data: Any) -> Dict[str, Any]:
        """Run the agent. Override in subclasses."""
        raise NotImplementedError("Subclasses must implement run()")


class Architect(BaseAgent):
    """
    Architect Agent - Designs the solution architecture.
    Takes a user request and produces a structured plan.
    """
    
    def run(self, mission: str) -> Dict[str, Any]:
        """
        Design the architecture for a given mission.
        
        Args:
            mission: The user's request/mission
            
        Returns:
            Architecture plan with strategy, components, and structure
        """
        self.logger.stage_start("architect", mission)
        
        try:
            # For now, create a structured architecture based on the mission
            # TODO: Replace with actual LLM call
            
            architecture = {
                "mission": mission,
                "strategy": f"Implement '{mission}' following Python best practices",
                "components": [
                    "main function",
                    "helper functions",
                    "documentation",
                    "error handling"
                ],
                "structure": {
                    "language": "python",
                    "pattern": "single_file" if "simple" in mission.lower() else "modular",
                    "requires_tests": True
                },
                "technical_approach": "Clean, readable code with proper documentation"
            }
            
            self.logger.stage_complete("architect", architecture)
            return architecture
            
        except Exception as e:
            self.logger.stage_error("architect", e)
            raise


class Builder(BaseAgent):
    """
    Builder Agent - Implements the code based on architecture.
    Takes architecture and produces actual code.
    """
    
    def run(self, architecture: Dict[str, Any]) -> Dict[str, Any]:
        """
        Build code based on architecture.
        
        Args:
            architecture: The architecture plan from Architect
            
        Returns:
            Implementation with code, files, and metadata
        """
        self.logger.stage_start("builder", architecture)
        
        try:
            mission = architecture.get("mission", "")
            
            # Generate actual code based on mission
            # TODO: Replace with actual LLM call
            
            if "hello" in mission.lower():
                code = '''#!/usr/bin/env python3
"""
Hello World Program
A simple demonstration of Python output.
"""

def main():
    """Print Hello, World! to console."""
    print("Hello, World!")


if __name__ == "__main__":
    main()
'''
            else:
                code = f'''#!/usr/bin/env python3
"""
{mission}
Auto-generated by Team Agent Builder.
"""

def main():
    """Main entry point."""
    # TODO: Implement {mission}
    print("Implementation for: {mission}")


if __name__ == "__main__":
    main()
'''
            
            implementation = {
                "code": code,
                "language": "python",
                "files": ["main.py"],
                "status": "built",
                "metadata": {
                    "lines_of_code": len(code.split('\n')),
                    "functions": code.count("def "),
                    "classes": code.count("class ")
                }
            }
            
            self.logger.stage_complete("builder", implementation)
            return implementation
            
        except Exception as e:
            self.logger.stage_error("builder", e)
            raise


class Critic(BaseAgent):
    """
    Critic Agent - Reviews code quality and provides feedback.
    Takes implementation and produces quality assessment.
    """
    
    def run(self, implementation: Dict[str, Any]) -> Dict[str, Any]:
        """
        Review the implementation.
        
        Args:
            implementation: The built code from Builder
            
        Returns:
            Quality review with score, issues, and recommendations
        """
        self.logger.stage_start("critic", implementation)
        
        try:
            code = implementation.get("code", "")
            
            # Perform code review
            # TODO: Replace with actual LLM call and static analysis
            
            issues = []
            strengths = []
            
            # Basic checks
            if "def main" in code:
                strengths.append("Has main entry point")
            else:
                issues.append("Missing main() function")
            
            if '"""' in code:
                strengths.append("Includes documentation")
            else:
                issues.append("Missing docstrings")
            
            if "if __name__" in code:
                strengths.append("Proper module structure")
            
            # Calculate quality score
            total_checks = 10
            passed_checks = len(strengths)
            quality_score = int((passed_checks / total_checks) * 100)
            
            review = {
                "quality_score": quality_score,
                "issues": issues,
                "strengths": strengths,
                "recommendation": "approved" if quality_score >= 70 else "needs_revision",
                "details": {
                    "readability": "good" if len(code.split('\n')) < 100 else "moderate",
                    "maintainability": "good",
                    "security": "no issues detected"
                }
            }
            
            self.logger.stage_complete("critic", review)
            return review
            
        except Exception as e:
            self.logger.stage_error("critic", e)
            raise


class Governance(BaseAgent):
    """
    Governance Agent - Ensures policy compliance.
    Takes review and validates against organizational policies.
    """
    
    def run(self, review: Dict[str, Any]) -> Dict[str, Any]:
        """
        Check governance and compliance.
        
        Args:
            review: The quality review from Critic
            
        Returns:
            Governance decision with compliance score and violations
        """
        self.logger.stage_start("governance", review)
        
        try:
            quality_score = review.get("quality_score", 0)
            issues = review.get("issues", [])
            
            # Check compliance policies
            # TODO: Add real policy checking
            
            violations = []
            policies_checked = [
                "code_quality",
                "security",
                "documentation",
                "testing"
            ]
            
            # Quality threshold policy
            if quality_score < 70:
                violations.append({
                    "policy": "minimum_quality",
                    "threshold": 70,
                    "actual": quality_score,
                    "severity": "high"
                })
            
            # Documentation policy
            if any("documentation" in issue.lower() for issue in issues):
                violations.append({
                    "policy": "documentation_required",
                    "severity": "medium"
                })
            
            compliance_score = 100 - (len(violations) * 20)
            compliance_score = max(0, compliance_score)
            
            decision = {
                "compliance_score": compliance_score,
                "decision": "approved" if len(violations) == 0 else "conditional",
                "violations": violations,
                "policies_checked": policies_checked,
                "requires_remediation": len(violations) > 0
            }
            
            self.logger.stage_complete("governance", decision)
            return decision
            
        except Exception as e:
            self.logger.stage_error("governance", e)
            raise


class Recorder(BaseAgent):
    """
    Recorder Agent - Creates audit trail and workflow record.
    Takes complete workflow and generates final record with signature.
    """
    
    def run(self, workflow_data: Dict[str, Any]) -> Dict[str, Any]:
        """
        Record the complete workflow.
        
        Args:
            workflow_data: Complete workflow with all stages
            
        Returns:
            Workflow record with signature and metrics
        """
        self.logger.stage_start("recorder", workflow_data)
        
        try:
            import hashlib
            import json
            from datetime import datetime
            
            # Extract data from workflow stages
            mission = workflow_data.get("mission", "")
            architect = workflow_data.get("architect", {})
            builder = workflow_data.get("builder", {})
            critic = workflow_data.get("critic", {})
            governance = workflow_data.get("governance", {})
            
            # Generate signature
            workflow_json = json.dumps(workflow_data, sort_keys=True)
            signature_hash = hashlib.sha256(workflow_json.encode()).hexdigest()
            
            # Calculate composite score
            quality_score = critic.get("quality_score", 0)
            compliance_score = governance.get("compliance_score", 0)
            overall_score = (quality_score + compliance_score) / 2
            
            record = {
                "workflow_id": self.workflow_id or f"wf_{datetime.now().strftime('%Y%m%d_%H%M%S')}",
                "timestamp": datetime.utcnow().isoformat() + "Z",
                "mission": mission,
                "signature": {
                    "hash": signature_hash,
                    "algorithm": "sha256"
                },
                "composite_score": {
                    "overall": round(overall_score, 2),
                    "quality": quality_score,
                    "compliance": compliance_score
                },
                "status": governance.get("decision", "unknown"),
                "stages_completed": 5,
                "metadata": {
                    "components": len(architect.get("components", [])),
                    "issues_found": len(critic.get("issues", [])),
                    "violations": len(governance.get("violations", []))
                }
            }
            
            self.logger.stage_complete("recorder", record)
            return record
            
        except Exception as e:
            self.logger.stage_error("recorder", e)
            raise